### PR TITLE
feat: Remove usage of rewire and access ejs.Template directly

### PR DESCRIPTION
**Pull request by daedal-knickerbockers**

### CODE REVIEW

**Comment by daedal-knickerbockers** [comment]
Seems to work as intended 😄

**Review by RyanZim — APPROVED** [review]
LGTM

**Comment by RyanZim** [comment]
@daedal-knickerbockers Just sent you an invite to be collaborator here (refs https://github.com/RyanZim/EJS-Lint/pull/75#issuecomment-708722116), feel free to merge this then.

**Comment by daedal-knickerbockers** [comment]
Done :-)

**Pull request merged**
