### PR TITLE
Update invalid.ejs

### PR DESCRIPTION
**Pull request by mahdisamadiyan**
Fixed close brace in code

### CODE REVIEW

**Comment by RyanZim** [comment]
The purpose of this file is to test how EJS handles broken code; the brace "mistake" is intentional. The file is literally named `invalid.ejs`.

**Comment by mahdisamadiyan** [comment]
Hello Mr. RyanZim
I apologize, I did not pay attention to the name of the file!
I know it is not correct to ask this question here, but I ran into a problem and I have to ask you!
When I convert the following code to ejs, it doesn't work and I can't get any answer from it, unfortunately:
`var sam = "test";
if(true){
    switch(sam){
       case 0:
          console.log("0");
          break;
       case 1:
           console.log("1");
           break
        case "test":
            console.log("its true");
    }
}`

**Comment by RyanZim** [comment]
Not sure what you're trying to do, but `console.log` will not result in output when used inside EJS.

**Comment by mahdisamadiyan** [comment]
Hello Mr. RyanZim
This code was for testing and not actually my original code.
The problem was with my code that instead of switching the zero index of the array, I was switching the array itself, and I thought that the switch case inside if in ejs doesn't work, but ejs works perfectly!
Your library is undoubtedly the best rendering library❤️👌

**Pull request closed without merging**
